#!/bin/bash

## Get data
STATUS="$(mpc status)"
COVER="/tmp/.music_cover.jpg"
MUSIC_DIR="/media/data/bima/lagu"

## Get status
get_status() {
	if [[ $STATUS == *"[playing]"* ]]; then
		#echo ""
		echo ""
	else
		echo ""
	fi
}

## Get song
get_song() {
	song=`mpc -f %title% current`
	if [[ -z "$song" ]]; then
		echo "Offline"
	else
		echo "   $song"
	fi	
}

## Get artist
get_artist() {
	artist=`mpc -f %artist% current`
	if [[ -z "$artist" ]]; then
		echo "Offline"
	else
		echo "   $artist"
	fi	
}

## Get genre
get_genre() {
	genre=`mpc -f %genre% current`
	if [[ -z "$genre" ]]; then
		echo "Offline"
	else
		echo "   $genre"
	fi	
}

## Get time
get_time() {
	time=`mpc status | grep "%)" | awk '{print $4}' | tr -d '(%)'`
	if [[ -z "$time" ]]; then
		echo "0"
	else
		echo "$time"
	fi	
}
get_ctime() {
	ctime=`mpc status | grep "#" | awk '{print $3}' | sed 's|/.*||g'`
	if [[ -z "$ctime" ]]; then
		echo "0:00"
	else
		echo "$ctime"
	fi	
}
get_ttime() {
	ttime=`mpc -f %time% current`
	if [[ -z "$ttime" ]]; then
		echo "0:00"
	else
		echo "$ttime"
	fi	
}

get_volume() {
    volume=`mpc status %volume%`
    if [[ -z "$volume" ]]; then
        echo "0"
    else
        echo "${volume::-1}"
    fi
}

## Get cover
get_cover() {
  album="$(mpc --format %album% current)"
  file="$(mpc --format %file% current)"
  album_dir="${file%/*}"
  album_dir="$MUSIC_DIR/$album_dir"
  found_covers="$(find "$album_dir" -type d -exec find {} -maxdepth 1 -type f \
  -iregex ".*/.*\(${album}\|cover\|folder\|artwork\|front\).*[.]\\(jpe?g\|png\|gif\|bmp\)" \; )"
  cover_path="$(echo "$found_covers" | head -n1)"
  if [ -n "$cover_path" ]; then
      echo "$cover_path"
  fi

  # If we still failed to find a cover image, we use the fallback
  if [ -z "$cover_path" ]; then
      echo "/home/jikope/.config/ncmpcpp/default_cover.png"
  fi
}

## Execute accordingly
if [[ "$1" == "--song" ]]; then
	get_song
elif [[ "$1" == "--artist" ]]; then
	get_artist
elif [[ "$1" == "--genre" ]]; then
	get_genre
elif [[ "$1" == "--status" ]]; then
	get_status
elif [[ "$1" == "--time" ]]; then
	get_time
elif [[ "$1" == "--ctime" ]]; then
	get_ctime
elif [[ "$1" == "--ttime" ]]; then
	get_ttime
elif [[ "$1" == "--cover" ]]; then
	get_cover
elif [[ "$1" == "--toggle" ]]; then
	mpc -q toggle
elif [[ "$1" == "--next" ]]; then
	{ mpc -q next; get_cover; }
elif [[ "$1" == "--prev" ]]; then
	{ mpc -q prev; get_cover; }
elif [[ "$1" == "--volume" ]]; then
	get_volume
fi
